import { useEffect, useRef, useState } from 'react';
import { X, Copy, ArrowUpRight, FileText, Plus, ChevronLeft, ChevronRight } from 'lucide-react';
import type { ArtifactDetail, EntityDetail, Note } from './types';
import type { Selection } from './Pages';
import { bytes, date, KindBadge, useData, Loading, KindIcon } from './shared';

export function Inspector({ selection, caseId, revision, onClose, onSelect, onError, notify, onUpdate }: { selection: Selection; caseId: string; revision: number; onClose: () => void; onSelect: (s: Selection | null) => void; onError: (s: string) => void; notify: (s: string) => void; onUpdate: () => void }) {
  const { data, loading } = useData<ArtifactDetail | EntityDetail>(`/cases/${caseId}/${selection.kind === 'artifact' ? 'artifacts' : 'entities'}/${selection.id}`, revision, onError);
  const { data: notes } = useData<Note[]>(`/cases/${caseId}/notes?node=${selection.id}`, revision, onError);
  const [tab, setTab] = useState('source'), [page, setPage] = useState(0), [note, setNote] = useState(''), [saving, setSaving] = useState(false);
  const focusLine = useRef<HTMLDivElement>(null);
  useEffect(() => { setTab('source'); setPage(Math.max(0, Math.floor(((selection.line || 1) - 1) / 200))); setNote(''); }, [selection.id, selection.line]);
  useEffect(() => { focusLine.current?.scrollIntoView({ block: 'center' }); }, [data, tab, page, selection.line]);
  const artifact = selection.kind === 'artifact' ? data as ArtifactDetail | null : null;
  const entity = selection.kind === 'entity' ? data as EntityDetail | null : null;
  const lines = artifact?.text.split('\n') || [];
  async function copy(text: string) { await window.atlas.copy(text); notify('Copied to clipboard.'); }
  async function addNote() { if (!note.trim()) return; setSaving(true); try { await window.atlas.api(`/cases/${caseId}/notes`, 'POST', { node_id: selection.id, body: note, tag: 'observation' }); setNote(''); onUpdate(); } catch (e) { onError((e as Error).message); } finally { setSaving(false); } }
  return <aside className="inspector" aria-label="Evidence inspector"><header><span className="section-label">EVIDENCE INSPECTOR</span><button aria-label="Close inspector" title="Close inspector (Esc)" onClick={onClose}><X size={17} /></button></header>
    {!data ? loading ? <Loading /> : <p className="muted inspector-padding">Evidence unavailable.</p> : <><div className="inspector-identity">{artifact ? <span className="file-type-icon"><FileText size={24} /></span> : <KindIcon kind={entity!.kind} size={25} />}<h2>{artifact?.name || entity?.value}</h2><button className="icon-button" aria-label="Copy selected value" onClick={() => copy(artifact?.sha256 || entity!.value)}><Copy size={15} /></button></div>
      {artifact ? <><div className="inspector-meta"><span className="extension">{artifact.extension}</span><span>{bytes(artifact.size)}</span><span>{artifact.metadata.encoding as string}</span></div><div className="hash-box"><span>SHA-256</span><code>{artifact.sha256}</code></div><div className="inspector-tabs">{['source', 'hex', 'metadata', 'indicators'].map(t => <button className={tab === t ? 'active' : ''} key={t} onClick={() => setTab(t)}>{t}</button>)}</div>
      <div className="inspector-content">
        {tab === 'source' && <><div className="source-caption">{artifact.metadata.encoding === 'binary-strings' ? 'Extracted strings · offsets refer to this derived view' : artifact.metadata.encoding === 'pdf-text' ? 'Extracted PDF text · logical line numbers' : 'Preserved text · logical line numbers'}{Boolean(artifact.metadata.text_truncated) && <strong> · Text capped at 4,000,000 characters</strong>}</div><div className="source-view">{lines.slice(page * 200, (page + 1) * 200).map((line, i) => { const number = page * 200 + i + 1; return <div className={selection.line === number ? 'source-line highlighted' : 'source-line'} key={number} ref={selection.line === number ? focusLine : null}><span>{number}</span><code>{line || ' '}</code></div>; })}</div><div className="source-pager"><span>{lines.length.toLocaleString()} logical lines</span><button disabled={page === 0} aria-label="Previous source lines" onClick={() => setPage(p => p - 1)}><ChevronLeft size={15} /></button><span>{page + 1}</span><button disabled={(page + 1) * 200 >= lines.length} aria-label="Next source lines" onClick={() => setPage(p => p + 1)}><ChevronRight size={15} /></button></div></>}
        {tab === 'hex' && <><div className="source-caption">First 512 bytes of the retained original</div><div className="hex-view">{Array.from({ length: Math.ceil(artifact.hex.length / 32) }, (_, i) => { const row = artifact.hex.slice(i * 32, (i + 1) * 32); return <div key={i}><span>{(i * 16).toString(16).padStart(8, '0')}</span><code>{row.match(/.{1,2}/g)?.join(' ')}</code><em>{row.match(/.{1,2}/g)?.map(b => { const c = parseInt(b, 16); return c >= 32 && c <= 126 ? String.fromCharCode(c) : '.'; }).join('')}</em></div>; })}</div></>}
        {tab === 'metadata' && <div className="metadata-view"><dl><dt>Source path</dt><dd>{artifact.path}</dd><dt>Imported UTC</dt><dd>{date(artifact.imported)}</dd><dt>Derivation</dt><dd>{artifact.relation}</dd><dt>Versions of source path</dt><dd>{artifact.versions.length}</dd></dl>{artifact.parent_id && <button className="text-button" onClick={() => onSelect({ id: artifact.parent_id!, kind: 'artifact' })}>Inspect parent evidence <ArrowUpRight size={14} /></button>}<pre>{JSON.stringify(artifact.metadata, null, 2)}</pre>{artifact.versions.length > 1 && artifact.versions.map(v => <button className="version-row" key={v.id} onClick={() => onSelect({ id: v.id, kind: 'artifact' })}><code>{v.sha256.slice(0, 18)}…</code><span>{date(v.imported)}</span></button>)}</div>}
        {tab === 'indicators' && <div className="inspector-entities">{artifact.entities.map(e => <button key={e.id} onClick={() => onSelect({ id: e.id, kind: 'entity' })}><KindIcon kind={e.kind} /><span>{e.value}</span><small>{e.mentions}</small></button>)}{!artifact.entities.length && <p className="muted">No indicators extracted.</p>}</div>}
        {artifact.findings.length > 0 && <section className="inspector-findings"><div className="section-label">ANALYSIS SIGNALS</div>{artifact.findings.map(f => <button key={f.id} onClick={() => { setTab('source'); setPage(Math.max(0, Math.floor((f.line - 1) / 200))); onSelect({ id: artifact.id, kind: 'artifact', line: f.line }); }}><span className={`severity ${f.severity}`}>{f.severity}</span><strong>{f.title}</strong><small>{f.detail}</small></button>)}</section>}
      </div></> : entity && <><div className="inspector-meta"><KindBadge kind={entity.kind} /><span>{entity.occurrences.length} shown mentions</span></div><div className="inspector-content"><div className="section-label provenance-label">OBSERVED IN SOURCE EVIDENCE</div><div className="provenance-list">{entity.occurrences.map((o, i) => <button key={i} onClick={() => onSelect({ id: o.artifact_id, kind: 'artifact', line: o.line })}><div><FileText size={14} /><strong>{o.name}</strong><span>:{o.line}</span><ArrowUpRight size={14} /></div><p>{o.excerpt}</p></button>)}</div>{entity.occurrences.length >= 1000 && <p className="muted">Showing the first 1,000 source mentions.</p>}</div></>}
      <section className="inspector-notes"><div className="section-label">ATTACHED OBSERVATIONS</div>{notes?.map(n => <p className="attached-note" key={n.id}>{n.body}<small>{date(n.created)} UTC</small></p>)}<textarea aria-label="Evidence note" placeholder="Attach an observation to this evidence…" value={note} maxLength={20000} onChange={e => setNote(e.target.value)} /><button className="text-button" disabled={saving || !note.trim()} onClick={addNote}><Plus size={14} /> Add observation</button></section>
    </>}
  </aside>;
}
